### ISSUE TITLE
Set sugarss as parser?

### ISSUE THREAD

**Issue by FezVrasta** [lmihaidaniel/rollup-plugin-postcss-export#1]
How?

**Comment by meszaros-lajos-gyorgy** [comment]
First install sugarss as a separate module by running `npm install sugarss --save`.

Then on top of your rollup config file include sugarss:

```javascript
var sugarss = require('sugarss');
```

In your rollup config you have to specify sugarss as the `parser` and set extensions to support the `.sss` files for your postcss() plugin:

```javascript
export default {
  entry: <your file>,
  ...,
  plugins: [
    postcss({
      extensions: ['.sss'],
      ...,
      parser: sugarss
    })
  ]
};
```

**Comment by FezVrasta** [comment]
thank you :)
