### ISSUE TITLE
output folder is not prepared at the start of the build

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [lmihaidaniel/rollup-plugin-postcss-export#2]
Hi!

Please look at the following files - github is having issues with zip files in 2017, so I cannot upload it:

**package.json**

```javascript
{
  "name": "issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c rollup.config.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "rollup": "^0.41.4",
    "rollup-plugin-postcss-export": "^0.3.2"
  }
}

```

**rollup.config.js**

```javascript
import postcss from 'rollup-plugin-postcss-export';

export default {
  entry: 'src/index.css',
  dest: 'dist/dummy',
  plugins: [
    postcss({
      extensions: ['.css'],
      output: './dist/x/style.css',
      plugins: []
    })
  ]
};
```

Create an `src` folder with an `index.css` inside with any content in it, then run `npm run build`

You will see, that `dist` will be created with `dummy` file inside, but the code will exit with an error stating that it cannot find the folder dist/x

The plugin should use something, like `mkdirp` to make sure, the output folder exists before trying to export the css

**Comment by lmihaidaniel** [comment]
Fixed in commit [create export folder if missing](https://github.com/lmihaidaniel/rollup-plugin-postcss-export/commit/a1c2b3d5e4df56e3ec94f2fd0904c8483acf54ca)

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!
