### ISSUE TITLE
Export transformed class names (css-modules)

### ISSUE THREAD

**Issue by flying-sheep** [lmihaidaniel/rollup-plugin-postcss-export#4]
i would like this code:

```js
import * as React from 'react'

import style from './style.css'

export default class C extends React.Component {
    render() {
        return <div className={style.c} />
    }
}
```

\+

```css
.c { color: blue; }
```

to compile to either this (with `options.output`):

```js
var style$1 = { c: '_c_b4z3z_1' };

class C extends react_2 {
    render() {
        return react_1("div", { className: style$1.c });
    }
}
```

\+

```css
._c_b4z3z_1 { color: blue; }
```

or this (no `options.output`)

```js
function __$injectStyle(css, exports) { ... }

var style$1 = __$injectStyle('._c_b4z3z_1 { color: blue; }', { c: '_c_b4z3z_1' });

[...]
```

**Comment by lmihaidaniel** [comment]
See 'Use with CSS modules' on Readme

**Comment by flying-sheep** [comment]
oh, so you rewrote it? it didn’t work with `output` before. (and `output` is now named `export` i assume?)

**Comment by lmihaidaniel** [comment]
Yes I rewrote it. `output `is now named `export` which can have a value as a string (the path where you want to export the css) or a boolean (when set to true the css will be exported in the same place as the rollup's js export)

**Comment by flying-sheep** [comment]
awesome! thanks to you we have a complete solution!
